name: Build and Deploy to VPS

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: Main

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          verbose: true

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts || echo "SSH keyscan failed, proceeding with existing keys"

      - name: Debug - check Jekyll build
        run: ls -la ./_site || echo "Jekyll build failed"

      - name: Deploy via rsync
        run: |
          set -ex
          echo "Deploying to ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_TARGET_DIR }}"
          rsync -avz --progress \
            --exclude='.git' \
            --exclude='.github' \
            ./_site/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_TARGET_DIR }} || echo "rsync failed"
        continue-on-error: true

      - name: Debug - check remote path
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "ls -la ${{ secrets.VPS_TARGET_DIR }}" || echo "Remote check failed"

      - name: Upload rsync log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rsync-log
          path: rsync.log
